config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'static_pages/about_activerecord_logs'
  get 'static_pages/about_server_logs'
  get 'static_pages/search_functions_summary'

  resources :users do
    resource :authorizations, only: [:edit, :update]
    resource :user_address, only: [:edit, :update, :destroy]
    resources :user_diaries
  end

  resources :user_posts, except: :show do
    resources :user_post_comments, only: [:index, :create, :destroy]
  end

  resources :events do
    collection do
      get :search
    end
  end

  resources :todos, only: :index do
    collection do
      get :search
    end
  end

  resources :schedules do
    collection do
      get :search
      get :sql_injection_search
    end
  end

  resources :shops, only: [:index]

  resources :products, only: [:index]

  resource :cart, only: [:show, :create, :destroy]

  root 'users#index'
end

app/controllers/user_addresses_controller.rb
class UserAddressesController < ApplicationController
  def edit
    @user = User.find(params[:user_id])
    @user_address = @user.user_address || @user.build_user_address
  end

  def update
    @user = User.find(params[:user_id])
    @user_address = @user.user_address || @user.build_user_address

    if @user_address.update(user_address_params)
      redirect_to @user, notice: t('user_addresses.flash.messages.updated') and return
    end
    render :edit
  end

  def destroy
    user = User.find(params[:user_id])

    user.user_address.destroy
    redirect_to user, notice: t('user_addresses.flash.messages.deleted')
  end

  private

  def user_address_params
    params
      .require(:user_address)
      .permit(:postal_code, :prefecture, :city, :address_line)
  end
end

app/views/user_addresses/edit.html.erb
<h1 class="fs-2 mb-5"><%= t('user_addresses.edit.title') %></h1>

<%= form_with model: @user_address, url: user_user_address_path(@user), method: :patch do |form| %>
  <div class="row mb-3">
    <%= form.label :postal_code, class: 'col-sm-3 col-form-label' %>
    <%= form.text_field :postal_code,
                        placeholder: t('user_addresses.edit.examples.postal_code'),
                        class: 'col-sm-9' %>
    <%= render partial: 'shared/attribute_error_messages',
               locals: { model: @user_address, attribute: :postal_code } %>
  </div>

  <div class="row mb-3">
    <p class="mb-1 p-0 text-end" id="user_address_prefecture-count-area">0/0</p>
    <%= form.label :prefecture, class: 'col-sm-3 col-form-label' %>
    <%= form.text_field :prefecture,
                        class: 'col-sm-9 js-text-count-target',
                        data: { max_length: UserAddress.max_length(:prefecture) }  %>
    <%= render partial: 'shared/attribute_error_messages',
               locals: { model: @user_address, attribute: :prefecture } %>
  </div>

  <div class="row mb-3">
    <p class="mb-1 p-0 text-end" id="user_address_city-count-area">0/0</p>
    <%= form.label :city, class: 'col-sm-3 col-form-label' %>
    <%= form.text_field :city,
                        class: 'col-sm-9 js-text-count-target',
                        data: { max_length: UserAddress.max_length(:city) }  %>
    <%= render partial: 'shared/attribute_error_messages',
               locals: { model: @user_address, attribute: :city } %>
  </div>

  <div class="row mb-3">
    <p class="mb-1 p-0 text-end" id="user_address_address_line-count-area">0/0</p>
    <%= form.label :address_line, class: 'col-sm-3 col-form-label' %>
    <%= form.text_field :address_line,
                        class: 'col-sm-9 js-text-count-target',
                        data: { max_length: UserAddress.max_length(:address_line) }  %>
    <%= render partial: 'shared/attribute_error_messages',
               locals: { model: @user_address, attribute: :address_line } %>
  </div>

  <div class="d-grid gap-3 d-md-flex justify-content-md-end">
    <%= form.submit t('user_addresses.edit.links.update'), class: 'btn btn-primary btn-sm' %>
    <% if @user_address.persisted? %>
      <%= link_to t('user_addresses.edit.links.delete'),
                  user_user_address_path(@user),
                  method: :delete,
                  data: { confirm: t('user_addresses.edit.confirm.delete') },
                  class: 'btn btn-danger btn-sm' %>
    <% end %>
  </div>
<% end %>