config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'static_pages/about_activerecord_logs'
  get 'static_pages/about_server_logs'
  get 'static_pages/search_functions_summary'

  resources :users do
    resource :authorizations, only: [:edit, :update]
    resource :user_address, only: [:edit, :update, :destroy]
    resources :user_diaries
  end

  resources :user_posts, except: :show do
    resources :user_post_comments, only: [:index, :create, :destroy]
  end

  resources :events do
    collection do
      get :search
    end
  end

  resources :todos, only: :index do
    collection do
      get :search
    end
  end

  resources :schedules do
    collection do
      get :search
      get :sql_injection_search
    end
  end

  resources :shops, only: [:index]

  resources :products, only: [:index]

  resource :cart, only: [:show, :create, :destroy]

  root 'users#index'
end

app/models/event.rb
class Event < ApplicationRecord
  MIN_MAX_PARTICIPANTS_SETTINGS = [{ label: '1~5', value: '1', range: 1..5 },
                                   { label: '6~10', value: '2', range: 6..10 },
                                   { label: '11~20', value: '3', range: 11..20 },
                                   { label: '21~30', value: '4', range: 21..30 },
                                   { label: '31~', value: '5', range: 31.. }]

  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 140 }
  validates :max_participants, presence: true
  validates :start_at, presence: true
  validates :finish_at, presence: true
  validates :host, presence: true, length: { maximum: 30 }

  validate :finish_at_after_start_at, if: :start_at_and_finish_at_present?

  scope :search, -> (events_search_params) do
    return if events_search_params.blank?

    title_like(events_search_params[:title])
      .start_after(events_search_params[:start_at])
      .finish_before(events_search_params[:finish_at])
      .max_participants_between(
        min_max_participants_range(events_search_params[:min_max_participants]))
      .body_like(events_search_params[:body])
      .host_like(events_search_params[:host])
  end
  scope :title_like, -> (title) { where('title LIKE ?', "%#{title}%") if title.present? }
  scope :start_after, -> (start_at) { where('? <= start_at', start_at) if start_at.present? }
  scope :finish_before, -> (finish_at) { where('finish_at <= ?', finish_at) if finish_at.present? }
  scope :max_participants_between, -> (min_max_participants) do
    where(max_participants: min_max_participants) if min_max_participants.present?
  end
  scope :body_like, -> (body) { where('body LIKE ?', "%#{body}%") if body.present? }
  scope :host_like, -> (host) { where('host LIKE ?', "%#{host}%") if host.present? }

  def self.min_max_participants_options
    MIN_MAX_PARTICIPANTS_SETTINGS.map do |min_max_participants_setting|
      [min_max_participants_setting[:label], min_max_participants_setting[:value]]
    end
  end

  def self.min_max_participants_range(selected_value)
    MIN_MAX_PARTICIPANTS_SETTINGS.find do |min_max_participants_setting|
      min_max_participants_setting[:value] == selected_value
    end[:range]
  end

  def start_and_finish_datetime
    "#{format_datetime(start_at)} ~ #{format_datetime(finish_at)}"
  end

  def format_datetime(datetime)
    datetime.strftime("%F %H:%M")
  end

  private

  def start_at_and_finish_at_present?
    start_at.present? && finish_at.present?
  end

  def finish_at_after_start_at
    errors.add(:finish_at, :invalid) unless start_at < finish_at
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events_search_params = events_search_params
    @pages, @events = paginate(active_record: Event.order(:id))
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def search
    @events_search_params = events_search_params
    @pages, @events = paginate(active_record: Event.search(@events_search_params).order(:id))

    render :index
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: t('events.flash.messages.created')
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event, notice: t('events.flash.messages.updated')
    else
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])

    event.destroy
    redirect_to events_path, notice: t('events.flash.messages.deleted', title: event.title)
  end

  private

  def event_params
    params
      .require(:event)
      .permit(:title, :body, :max_participants, :start_at, :finish_at)
      .merge(host: current_user.name)
  end

  def events_search_params
    params
      .fetch(:search, {})
      .permit(:title, :start_at, :finish_at, :min_max_participants, :body, :host)
  end
end

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <div class="row mb-3">
    <p class="mb-1 p-0 text-end" id="event_title-count-area">0/0</p>
    <%= form.label :title, class: 'col-sm-2 col-form-label' %>
    <%= form.text_field :title,
                        class: 'col-sm-10 js-text-count-target',
                        data: { max_length: Event.max_length(:title) }  %>
    <%= render partial: 'shared/attribute_error_messages',
               locals: { model: event, attribute: :title } %>
  </div>

  <div class="row mb-3">
    <%= form.label :start_at, class: 'col-sm-2 col-form-label' %>
    <%= form.datetime_field :start_at, class: 'col-sm-10' %>
    <%= render partial: 'shared/attribute_error_messages',
               locals: { model: event, attribute: :start_at } %>
  </div>

  <div class="row mb-3">
    <%= form.label :finish_at, class: 'col-sm-2 col-form-label' %>
    <%= form.datetime_field :finish_at, class: 'col-sm-10' %>
    <%= render partial: 'shared/attribute_error_messages',
               locals: { model: event, attribute: :finish_at } %>
  </div>

  <div class="row mb-3">
    <%= form.label :max_participants, class: 'col-sm-2 col-form-label' %>
    <%= form.number_field :max_participants, class: 'col-sm-10' %>
    <%= render partial: 'shared/attribute_error_messages',
               locals: { model: event, attribute: :max_participants } %>
  </div>

  <div class="row mb-3">
    <p class="mb-1 p-0 text-end" id="event_body-count-area">0/0</p>
    <%= form.label :body, class: 'col-sm-2 col-form-label' %>
    <%= form.text_area :body,
                        class: 'col-sm-10 js-text-count-target',
                        data: { max_length: Event.max_length(:body) }  %>
    <%= render partial: 'shared/attribute_error_messages',
               locals: { model: event, attribute: :body } %>
  </div>

  <div class="d-grid gap-3 d-md-flex justify-content-md-end">
    <%= form.submit t('events.form.links.submit'), class: 'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="events">
  <h1 class="fs-2 mb-5"><%= t('events.edit.title') %></h1>

  <%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
<div class="events">
  <h1 class="fs-2 mb-0"><%= t('events.index.title') %></h1>

  <div class="d-grid gap-3 d-md-flex justify-content-md-end mb-2">
    <% if current_user.authorized?('events', 'search') %>
      <button class="btn btn-primary btn-sm js-toggle-form-button">検索</button>
    <% end %>
    <% if current_user.authorized?('events', 'new') %>
      <%= link_to t('events.index.links.new'), new_event_path, class: 'btn btn-primary btn-sm' %>
    <% end %>
  </div>

  <%= form_with scope: :search,
                url: search_events_path,
                method: :get,
                local: true,
                class: 'mb-4 p-4 border js-toggle-form-target' do |form| %>
    <div class="row mb-3">
      <%= form.label :title, t('events.index.labels.title'), class: 'col-sm-3 col-form-label' %>
      <%= form.text_field :title, value: @events_search_params[:title], class: 'col-sm-9' %>
    </div>

    <div class="row mb-3">
      <%= form.label :start_at, t('events.index.labels.start_at'),
                     class: 'col-sm-3 col-form-label' %>
      <%= form.datetime_field :start_at,
                              value: @events_search_params[:start_at],
                              class: 'col-sm-9' %>
    </div>

    <div class="row mb-3">
      <%= form.label :finish_at,
                     t('events.index.labels.finish_at'),
                     class: 'col-sm-3 col-form-label' %>
      <%= form.datetime_field :finish_at,
                              value: @events_search_params[:finish_at],
                              class: 'col-sm-9' %>
    </div>

    <div class="row mb-3">
      <%= form.label :min_max_participants,
                     t('events.index.labels.min_max_participants'),
                     class: 'col-sm-3 col-form-label' %>
      <%= form.select :min_max_participants,
                      Event.min_max_participants_options,
                      { include_blank: true,
                        selected: @events_search_params[:min_max_participants] },
                      class: 'col-sm-9' %>
    </div>

    <div class="row mb-3">
      <%= form.label :body, t('events.index.labels.body'), class: 'col-sm-3 col-form-label' %>
      <%= form.text_field :body, value: @events_search_params[:body], class: 'col-sm-9' %>
    </div>

    <div class="row mb-3">
      <%= form.label :host, t('events.index.labels.host'), class: 'col-sm-3 col-form-label' %>
      <%= form.text_field :host, value: @events_search_params[:host], class: 'col-sm-9' %>
    </div>

    <div class="d-grid gap-3 d-md-flex justify-content-md-end">
      <%= form.submit t('events.index.links.search'), class: 'btn btn-primary btn-sm' %>
      <%= link_to t('events.index.links.reset'), events_path, class: 'btn btn-danger btn-sm' %>
    </div>
  <% end %>

  <table class="table table-striped border">
    <thead>
      <tr>
        <th><%= Event.human_attribute_name(:id) %></th>
        <th><%= Event.human_attribute_name(:title) %></th>
        <th><%= t('events.index.labels.start_and_finish_datetime') %></th>
        <th><%= Event.human_attribute_name(:max_participants) %></th>
        <th><%= Event.human_attribute_name(:body) %></th>
        <th><%= Event.human_attribute_name(:host) %></th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.id %></td>
          <td><%= link_to event.title, event, class: 'text-decoration-none' %></td>
          <td><%= event.start_and_finish_datetime %></td>
          <td><%= event.max_participants %></td>
          <td><%= event.body %></td>
          <td><%= event.host %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

 <% if @events.empty? %>
   <%= t('events.index.messages.empty_event') %>
 <% end %>

  <%= render 'shared/pagination', pages: @pages %>
</div>

app/views/events/new.html.erb
<div class="events">
  <h1 class="fs-2 mb-5"><%= t('events.new.title')%></h1>

  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<div class="events">
  <h1 class="fs-2 mb-5"><%= t('events.show.title') %></h1>

  <div class="event-profile">
    <p>
      <%= "#{Event.human_attribute_name(:title)}:" %>
      <%= @event.title %>
    </p>

    <p>
      <%= "#{t('events.show.labels.start_and_finish_datetime')}:" %>
      <%= @event.start_and_finish_datetime %>
    </p>

    <p>
      <%= "#{Event.human_attribute_name(:max_participants)}:" %>
      <%= @event.max_participants %>
    </p>

    <p>
      <%= "#{Event.human_attribute_name(:body)}:" %>
      <%= @event.body %>
    </p>

    <p>
      <%= "#{Event.human_attribute_name(:host)}:" %>
      <%= @event.host %>
    </p>

  <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-2">
    <% if current_user.authorized?('events', 'edit') %>
      <%= link_to t('events.show.links.edit'),
                  edit_event_path(@event),
                  class: 'btn btn-primary btn-sm' %>
    <% end %>

    <% if current_user.authorized?('events', 'destroy') %>
      <%= link_to t('events.show.links.delete'),
                  event_path(@event),
                  method: :delete,
                  data: { confirm: t('events.show.confirm.delete', title: @event.title) },
                  class: 'btn btn-danger btn-sm' %>
    <% end %>
  </div>
</div>