config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'static_pages/about_activerecord_logs'
  get 'static_pages/about_server_logs'
  get 'static_pages/search_functions_summary'

  resources :users do
    resource :authorizations, only: [:edit, :update]
    resource :user_address, only: [:edit, :update, :destroy]
    resources :user_diaries
  end

  resources :user_posts, except: :show do
    resources :user_post_comments, only: [:index, :create, :destroy]
  end

  resources :events do
    collection do
      get :search
    end
  end

  resources :todos, only: :index do
    collection do
      get :search
    end
  end

  resources :schedules do
    collection do
      get :search
      get :sql_injection_search
    end
  end

  resources :shops, only: [:index]

  resources :products, only: [:index]

  resource :cart, only: [:show, :create, :destroy]

  root 'users#index'
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  has_many :user_authorizations
  has_many :users, through: :user_authorizations, dependent: :destroy

  validates :controller, presence: true
  validates :action, presence: true
end

app/models/user.rb
require 'digest/sha2'

class User < ApplicationRecord
  has_many :user_authorizations
  has_many :authorizations, through: :user_authorizations, dependent: :destroy
  has_many :user_diaries, dependent: :destroy
  has_many :user_posts, dependent: :destroy
  has_one :user_address, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  enum gender: {
    men: 0,
    women: 1,
    others: 2
  }

  validates :name, presence: true, length: { maximum: 30 }
  validates :email,
            presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :gender, inclusion: { in: genders.keys }
  validates :birthday, presence: true
  validates :password, length: { minimum: 8 }, confirmation: true
  validates :password_confirmation, presence: true

  before_save :downcase_email

  has_secure_password

  def authorized?(controller, action)
    authorizations.any? do |authorization|
      authorization.controller == controller && authorization.action == action
    end
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  def edit
    @user = User.find(params[:user_id])
    @authorizations = Authorization.all
  end

  def update
    @user = User.find(params[:user_id])

    @user.authorization_ids = authorization_params[:authorization_ids]
    redirect_to @user, notice: t('authorizations.flash.messages.change_user_authorizations.success')
  end

  private

  def authorization_params
    params.require(:user).permit(authorization_ids: [])
  end
end

app/views/authorizations/edit.html.erb
<h1 class="fs-2 mb-4"><%= t('authorizations.edit.title') %></h1>

<%= form_with model: @user, url: user_authorizations_path(@user) do |form| %>
  <table class="table table-striped border">
    <thead>
      <tr>
        <th>Controller</th>
        <th>Action</th>
        <th>アクセス権限</th>
      </tr>
    </thead>
    <tbody>
      <%= form.collection_check_boxes(:authorization_ids,
                                      @authorizations,
                                      :id,
                                      :action,
                                      include_hidden: false) do |authorization| %>
        <%= authorization.label do %>
          <tr>
            <td><%= authorization.object.controller %></td>
            <td><%= authorization.object.action %></td>
            <td><%= authorization.check_box %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <div class="d-grid gap-2 d-md-flex justify-content-md-end mt-2">
    <%= form.submit class: 'btn btn-primary btn-sm' %>
  </div>
<% end %>